[source::...\\*.(?i)(xlsx)]
unarchive_cmd = powershell.exe -ExecutionPolicy RemoteSigned -File "$SPLUNK_HOME\etc\apps\TA-xlsx\bin\Stream-Xlsx.ps1"
unarchive_cmd_start_mode = direct
sourcetype = preprocess-xlsx
NO_BINARY_CHECK = true

[source::.../*.(?i)(xlsx)]
unarchive_cmd = $SPLUNK_HOME/etc/apps/TA-xlsx/bin/Stream-Xlsx.ps1
unarchive_cmd_start_mode = direct
sourcetype = preprocess-xlsx
NO_BINARY_CHECK = true

[preprocess-xlsx]
invalid_cause = archive
is_valid = False
LEARN_MODEL = false

[xlsx]
SHOULD_LINEMERGE = false
INDEXED_EXTRACTIONS = csv
KV_MODE = none
DATETIME_CONFIG = NONE
